services:
  flyway:
    build: flyway
    command:
      - "-url=jdbc:postgresql://postgres:5432/db"
      - "-user=user"
      - "-password=password"
      - "-connectRetries=60"
      - "migrate"
    depends_on:
      - postgres
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  redis:
    image: redis:7.0.12
    ports:
      - 6379:6379
