services:
  flyway:
    image: flyway/flyway:latest
    command:
      - "-url=jdbc:postgresql://postgres:5432/db"
      - "-user=user"
      - "-password=password"
      - "-connectRetries=60"
      - "migrate"
    depends_on:
      - postgres
    volumes:
      - ./flyway/sql:/flyway/sql
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
